### ISSUE TITLE
Metal Stud Layer for Standard Wall Construction

### ISSUE THREAD

**Issue by KBigart** [ThorntonTomasetti/Beacon#3]
**Great tool --- looks very promising so far. Thank you for your work on this.**

Immediate thing we ran into was the metal stud layer for walls and values drastically skewing results. For our standard wall types, metal stud layer is set to the Structural Material, and I believe Beacon is reading the entire volume of stud space as if its a solid of the Metal material asset, not just the physical extruded stud. 

Whats the solution for this... multiply the GWP by the actual volume ratio of the stud solid vs solid mass? That is how we initially solved it, but not sure if a ratio or something else could be incorporated similar to the metal decking solution.

**Concrete structural building before:**
![image](https://user-images.githubusercontent.com/43385221/72293064-b878cf80-3620-11ea-8c6e-b4ba85bd008e.png)

**Adjusted to 1/100th for stud values, which is much closer to reality.**
![image](https://user-images.githubusercontent.com/43385221/72293140-de9e6f80-3620-11ea-8b17-83c15b62f494.png)

**Comment by ktam-tt** [comment]
Yes, your approach of factoring your GWP down to make up for Revit reporting the entire mass as the volume, is what I would have done.

We are considering adding a percentage to each row to allow for accounting for wastage, connection material, etc, and that can potentially solve this as well. In that case, you can use it to decrease your volume accordingly and use the correct GWP.

**Comment by KBigart** [comment]
I like the percentage idea. Keeping GWP consistent (and maybe including even a future library of standard GWP values or something) then allowing percentage would be great. It also would allow someone to negate a material completely with a 0% rather than introducing some other way to do that. (we had some floors that were just planter materials i wanted to negate for example). Thanks for the response!

**Comment by ktam-tt** [comment]
Implemented Factor to increase/decrease volume. Deployed.
