### ISSUE TITLE
SI Units

### ISSUE THREAD

**Issue by simonperks** [ThorntonTomasetti/Beacon#4]
Hi all,

I've just started playing with your software in the UK to compare it to similar that I have access to. I've come up against a problem with an issue of Beacon reading the steel density in UK SI units.

The density of steel within my Revit file is set to 7,852 kg/m^3
This converts to approximately 490 PCF
Beacon reads the steel density as 15,771 PCF

Something is clearly wrong here. Am I doing something incorrectly or is this a bug in the software? Does anyone know of a work around? I'd quite like to avoid having to convert my model to American Imperial units if possible.

Many thanks!

**Comment by ktam-tt** [comment]
This is a bug, units are always tricky. Revit UK SI material returns unit weight in KILONEWTONS_PER_CUBIC_METER, and density in KILOGRAMS_PER_CUBIC_METER. Force and mass conversion factors are obviously different, so I need to account for that.

Good catch. Thanks!

**Comment by ktam-tt** [comment]
Fixed and deployed.

**Comment by simonperks** [comment]
> Fixed and deployed.

Thanks very much ktam-tt, updated and working fine now! Cheers!
